// Performance pass over the generated LP HTML (pages.ts stays exactly as Viktor generates it).
// Only touches how assets load: fonts, hero image format/priority, lazy below-fold images.
// Visible copy, offers, phone numbers, call buttons and tracking tags are left byte-for-byte as-is.

const GOOGLE_FONTS_LINK =
  /<link href="https:\/\/fonts\.googleapis\.com\/css2\?family=Oswald[^"]*" rel="stylesheet">/;

// Self-hosted Oswald (variable, latin subset, same file Google Fonts serves for 500 and 700).
const FONT_URL = "/fonts/oswald-latin-var.woff2";
const FONT_FACE =
  `<style>@font-face{font-family:Oswald;font-style:normal;font-weight:500 700;font-display:swap;` +
  `src:url(${FONT_URL}) format("woff2");unicode-range:U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,` +
  `U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD}</style>`;

// Hero background JPGs that have .avif/.webp siblings in /public/images/lp
// (generated by scripts/lp-hero-images.mjs).
const HERO_URL = /url\('?(\/images\/lp\/[^)']+?)\.jpg'?\)/;

// A-variant heroes that also have a phone crop ("-m"): full height, cropped around the 70%
// background-position, so on screens <=480px it paints the exact same region with fewer bytes.
const MOBILE_CROP = new Set([
  "/images/lp/phx18-1400",
  "/images/lp/phx7-1400",
  "/images/lp/final-pest-jordan-approved-scorpion-blacklight-blockwall-1400",
  "/images/lp/phx29-1400",
  "/images/lp/phx2-1400",
]);
const PHONE = "(max-width:480px)";

function imageSet(base: string, jpgBase = base) {
  return (
    `image-set(url('${base}.avif') type("image/avif"),url('${base}.webp') type("image/webp"),` +
    `url('${jpgBase}.jpg') type("image/jpeg"))`
  );
}

export function optimizeLp(html: string): string {
  let out = html;

  // Which A/B variant this page renders ("K='B';r()" at the end of the page script).
  const variant = (out.match(/K='([A-Z])';r\(\)/) || [])[1] || "A";

  // 1. Hero style block: add AVIF/WebP overrides after it (older browsers keep the JPG).
  let lcpBase: string | null = null;
  let lcpCrop = false;
  out = out.replace(/<style>(\.hero\.vA\{[^<]*)<\/style>/, (block, css: string) => {
    const overrides: string[] = [];
    for (const m of css.matchAll(/([^{}]+)\{([^{}]*)\}/g)) {
      const selector = m[1];
      const url = m[2].match(HERO_URL);
      if (!url) continue;
      const crop = selector === ".hero.vA" && MOBILE_CROP.has(url[1]);
      overrides.push(`${selector}{background-image:${imageSet(url[1])}}`);
      if (crop) overrides.push(`@media${PHONE}{${selector}{background-image:${imageSet(url[1] + "-m", url[1])}}}`);
      if (!lcpBase && selector.startsWith(`.hero.v${variant}`)) {
        lcpBase = url[1];
        lcpCrop = crop;
      }
    }
    return overrides.length ? `${block}<style>${overrides.join("")}</style>` : block;
  });

  // 2. Render the final hero variant class up front (the page script sets the same class on load),
  //    so -b pages don't fetch the A hero first.
  if (variant !== "A") {
    out = out.replace('<div class="hero vA" id="hero">', `<div class="hero v${variant}" id="hero">`);
  }

  // 3. Head: preload the LCP hero + font, replace render-blocking Google Fonts CSS.
  const heroPreload = (href: string, media = "") =>
    `<link rel="preload" as="image" href="${href}" type="image/avif" fetchpriority="high"${media ? ` media="${media}"` : ""}>`;
  let preloads = "";
  if (lcpBase && lcpCrop) {
    preloads = heroPreload(`${lcpBase}-m.avif`, PHONE) + heroPreload(`${lcpBase}.avif`, "(min-width:481px)");
  } else if (lcpBase) {
    preloads = heroPreload(`${lcpBase}.avif`);
  }
  preloads += `<link rel="preload" as="font" href="${FONT_URL}" type="font/woff2" crossorigin>`;
  out = out.replace(/(<meta name="viewport"[^>]*>)/, `$1\n${preloads}`);
  out = out.replace(GOOGLE_FONTS_LINK, FONT_FACE);

  // 4. Below-the-fold content images: lazy + async decode.
  out = out.replace(/<img id="pimg" /, '<img id="pimg" loading="lazy" decoding="async" ');

  return out;
}
