/** @type {import('next').NextConfig} */
const nextConfig = {
  eslint: { ignoreDuringBuilds: true },
  typescript: { ignoreBuildErrors: false },
  images: {
    remotePatterns: [
      { protocol: "https", hostname: "getyourbucksworth.com" },
      { protocol: "https", hostname: "www.getyourbucksworth.com" },
      { protocol: "https", hostname: "w74.506.myftpupload.com" },
      { protocol: "https", hostname: "*.myftpupload.com" },
    ],
    formats: ["image/avif", "image/webp"],
  },
  async headers() {
    return [
      {
        source: "/(.*)",
        headers: [
          { key: "X-Content-Type-Options", value: "nosniff" },
          { key: "X-Frame-Options", value: "SAMEORIGIN" },
          { key: "X-XSS-Protection", value: "1; mode=block" },
          { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
          {
            key: "Strict-Transport-Security",
            value: "max-age=31536000; includeSubDomains",
          },
          {
            key: "Permissions-Policy",
            value:
              "camera=(), microphone=(), geolocation=(self), interest-cohort=()",
          },
        ],
      },
    ];
  },
  async redirects() {
    return [
        // ── Non-www → www redirect (must be first) ──
        {
          source: '/:path*',
          has: [{ type: 'host', value: 'getyourbucksworth.com' }],
          destination: 'https://www.getyourbucksworth.com/:path*',
          permanent: true,
        },
        // Old WordPress sitemap redirects → new sitemap.xml
        { source: "/sitemap_index.xml", destination: "/sitemap.xml", permanent: true },
        { source: "/page-sitemap.xml", destination: "/sitemap.xml", permanent: true },
        { source: "/post-sitemap.xml", destination: "/sitemap.xml", permanent: true },
        // Service root URL redirects (Footer links)
        { source: "/pest-and-termite", destination: "/phoenix-az/pest-and-termite", permanent: true },
        { source: "/air-conditioning-and-heating", destination: "/phoenix-az/air-conditioning-and-heating", permanent: true },
        { source: "/air-conditioning", destination: "/phoenix-az/air-conditioning-and-heating", permanent: true },
        { source: "/plumbing-and-water-heaters", destination: "/phoenix-az/plumbing-and-water-heaters", permanent: true },
        { source: "/weed-and-lawn-care", destination: "/phoenix-az/weed-and-lawn-care", permanent: true },
        // Legacy page redirects
        { source: "/contact", destination: "/request-service", permanent: true },
        { source: "/careers", destination: "/about", permanent: true },
        // Old /phoenix/ service pages → specific new pages (fixed: was generic /phoenix-az)
        { source: "/phoenix/pest-control", destination: "/phoenix-az/pest-and-termite", permanent: true },
        { source: "/phoenix/pest-control/rodent-control", destination: "/phoenix-az/pest-and-termite/rodent-exclusion", permanent: true },
        { source: "/phoenix/hvac-services/residential", destination: "/phoenix-az/air-conditioning-and-heating", permanent: true },
        { source: "/phoenix/hvac-services/residential/ac-services/repair", destination: "/phoenix-az/air-conditioning-and-heating/ac-repair", permanent: true },
        { source: "/phoenix/refrigeration/walk-in-coolers-freezers", destination: "/phoenix-az/air-conditioning-and-heating", permanent: true },
        { source: "/phoenix/refrigeration/ice-machines", destination: "/phoenix-az/air-conditioning-and-heating", permanent: true },
        { source: "/phoenix/hvac-services/indoor-air-quality/carbon-monoxide-detection", destination: "/phoenix-az/air-conditioning-and-heating", permanent: true },
        // Old /phoenix/ pages that were 404 → now redirected
        { source: "/phoenix/lawn-weed-control", destination: "/phoenix-az/weed-and-lawn-care", permanent: true },
        { source: "/phoenix/plumbing", destination: "/phoenix-az/plumbing-and-water-heaters", permanent: true },
        // ── Phase 3: Old /phoenix/* deep paths → specific new pages (found via GSC, 2026-06-14) ──
        { source: "/phoenix/hvac-services/residential/ac-services/maintenance", destination: "/phoenix-az/air-conditioning-and-heating/ac-maintenance", permanent: true },
        { source: "/phoenix/hvac-services/maintenance", destination: "/phoenix-az/air-conditioning-and-heating/ac-maintenance", permanent: true },
        { source: "/phoenix/hvac-services/residential/ac-services/installation", destination: "/phoenix-az/air-conditioning-and-heating/ac-installation", permanent: true },
        { source: "/phoenix/hvac-services/residential/ac-services/replacement", destination: "/phoenix-az/air-conditioning-and-heating/ac-installation", permanent: true },
        { source: "/phoenix/hvac-services/residential/ac-services", destination: "/phoenix-az/air-conditioning-and-heating", permanent: true },
        { source: "/phoenix/hvac-services/repair", destination: "/phoenix-az/air-conditioning-and-heating/ac-repair", permanent: true },
        { source: "/phoenix/hvac-services/residential/heating-services/repair", destination: "/phoenix-az/air-conditioning-and-heating/heating-repair", permanent: true },
        { source: "/phoenix/hvac-services/residential/heating-services/replacement", destination: "/phoenix-az/air-conditioning-and-heating/heating-repair", permanent: true },
        { source: "/phoenix/hvac-services/residential/heating-services/maintenance", destination: "/phoenix-az/air-conditioning-and-heating/ac-maintenance", permanent: true },
        { source: "/phoenix/hvac-services/residential/heating-services", destination: "/phoenix-az/air-conditioning-and-heating", permanent: true },
        { source: "/phoenix/hvac-services/residential/heat-pump-services/maintenance", destination: "/phoenix-az/air-conditioning-and-heating/ac-maintenance", permanent: true },
        { source: "/phoenix/hvac-services/residential/heat-pump-services/repair", destination: "/phoenix-az/air-conditioning-and-heating/ac-repair", permanent: true },
        { source: "/phoenix/hvac-services/residential/heat-pump-services/installation", destination: "/phoenix-az/air-conditioning-and-heating/ac-installation", permanent: true },
        { source: "/phoenix/hvac-services/residential/heat-pump-services", destination: "/phoenix-az/air-conditioning-and-heating", permanent: true },
        { source: "/phoenix/hvac-services/indoor-air-quality/humidifiers", destination: "/phoenix-az/air-conditioning-and-heating", permanent: true },
        { source: "/phoenix/hvac-services/indoor-air-quality/air-puriiers", destination: "/phoenix-az/air-conditioning-and-heating", permanent: true },
        { source: "/phoenix/refrigeration", destination: "/phoenix-az/air-conditioning-and-heating", permanent: true },
        { source: "/phoenix/pest-control/scorpion-extermination", destination: "/phoenix-az/pest-and-termite/scorpion-control", permanent: true },
        { source: "/phoenix/pest-control/mosquito-control", destination: "/phoenix-az/pest-and-termite/mosquito-control", permanent: true },
        { source: "/phoenix/pest-control/roach-control", destination: "/phoenix-az/pest-and-termite/roach-elimination", permanent: true },
        { source: "/phoenix/pest-control/spider-control", destination: "/phoenix-az/pest-and-termite/spider-prevention", permanent: true },
        { source: "/phoenix/pest-control/termite-control", destination: "/phoenix-az/pest-and-termite/termite-treatment", permanent: true },
        { source: "/phoenix/pest-control/ant-control", destination: "/phoenix-az/pest-and-termite/ant-control", permanent: true },
        { source: "/phoenix/plumbing/tankless", destination: "/phoenix-az/plumbing-and-water-heaters/water-heater-repair", permanent: true },
        { source: "/phoenix/plumbing/reverse-osmosis", destination: "/phoenix-az/plumbing-and-water-heaters", permanent: true },
        { source: "/phoenix/plumbing/water-filtration-systems", destination: "/phoenix-az/plumbing-and-water-heaters", permanent: true },
        // Old generic pest pages → specific pest page
        { source: "/centipede-pest-control", destination: "/phoenix-az/pest-and-termite", permanent: true },
        { source: "/bed-bug-pest-control", destination: "/phoenix-az/pest-and-termite", permanent: true },
        { source: "/silverfish-pest-control", destination: "/phoenix-az/pest-and-termite", permanent: true },
        { source: "/bee-pest-control", destination: "/phoenix-az/pest-and-termite/bee-wasp-removal", permanent: true },
        { source: "/bird-pest-control", destination: "/phoenix-az/pest-and-termite", permanent: true },
        // Old misc pages
        { source: "/company", destination: "/about", permanent: true },
        { source: "/amana", destination: "/phoenix-az/air-conditioning-and-heating", permanent: true },
        { source: "/day-night", destination: "/phoenix-az/air-conditioning-and-heating", permanent: true },
        { source: "/accessibility-statement", destination: "/about", permanent: true },
        // Old city-specific pages that were 404
        { source: "/pest-control-peoria-az", destination: "/peoria-az/pest-and-termite", permanent: true },
        { source: "/pest-control-apache-junction-az", destination: "/apache-junction-az/pest-and-termite", permanent: true },
        { source: "/pest-control-apache-junction", destination: "/apache-junction-az/pest-and-termite", permanent: true },
        // Phase 2: Old WordPress service page redirects (top broken internal link targets)
        { source: "/pest-control-az", destination: "/phoenix-az/pest-and-termite", permanent: true },
        { source: "/air-conditioning-maintenance", destination: "/phoenix-az/air-conditioning-and-heating/ac-maintenance", permanent: true },
        { source: "/air-ducts", destination: "/phoenix-az/air-conditioning-and-heating/ductwork", permanent: true },
        { source: "/spider-pest-control", destination: "/phoenix-az/pest-and-termite/spider-prevention", permanent: true },
        { source: "/ant-pest-control", destination: "/phoenix-az/pest-and-termite/ant-control", permanent: true },
        { source: "/air-conditioning-installation", destination: "/phoenix-az/air-conditioning-and-heating/ac-installation", permanent: true },
        { source: "/news", destination: "/blog", permanent: true },
        { source: "/products", destination: "/", permanent: true },
        { source: "/roof-rats-pest-control", destination: "/phoenix-az/pest-and-termite/rodent-exclusion", permanent: true },
        { source: "/heating-repairs", destination: "/phoenix-az/air-conditioning-and-heating/heating-repair", permanent: true },
        { source: "/wasp-pest-control", destination: "/phoenix-az/pest-and-termite/bee-wasp-removal", permanent: true },
        { source: "/ductless-hvac", destination: "/phoenix-az/air-conditioning-and-heating/mini-split-systems", permanent: true },
        { source: "/goodman", destination: "/phoenix-az/air-conditioning-and-heating", permanent: true },
        { source: "/service-area", destination: "/sitemap-page", permanent: true },
        { source: "/millipede-pest-control", destination: "/phoenix-az/pest-and-termite", permanent: true },
        { source: "/fly-pest-control", destination: "/phoenix-az/pest-and-termite", permanent: true },
        { source: "/squirrel-pest-control", destination: "/phoenix-az/pest-and-termite/rodent-exclusion", permanent: true },
        { source: "/roach-pest-control", destination: "/phoenix-az/pest-and-termite", permanent: true },
        { source: "/termite-inspections", destination: "/phoenix-az/pest-and-termite/termite-treatment", permanent: true },
        { source: "/yellow-jackets-pest-control", destination: "/phoenix-az/pest-and-termite/bee-wasp-removal", permanent: true },
        { source: "/commercial-refrigeration", destination: "/phoenix-az/air-conditioning-and-heating", permanent: true },
        { source: "/reviews", destination: "/", permanent: true },
        { source: "/hornet-pest-control", destination: "/phoenix-az/pest-and-termite/bee-wasp-removal", permanent: true },
        { source: "/scorpion-control", destination: "/phoenix-az/pest-and-termite/scorpion-control", permanent: true },
        { source: "/scorpion-pest-control", destination: "/phoenix-az/pest-and-termite/scorpion-control", permanent: true },
        { source: "/pest-control", destination: "/phoenix-az/pest-and-termite", permanent: true },
        { source: "/termite-control", destination: "/phoenix-az/pest-and-termite/termite-treatment", permanent: true },
        { source: "/plumbing", destination: "/phoenix-az/plumbing-and-water-heaters", permanent: true },
        { source: "/weed-control", destination: "/phoenix-az/weed-and-lawn-care", permanent: true },
        // City-specific old WordPress pages
        { source: "/plumbing-queen-creek", destination: "/queen-creek-az/plumbing-and-water-heaters", permanent: true },
        { source: "/pest-control-san-tan-valley-az", destination: "/san-tan-valley-az/pest-and-termite", permanent: true },
        { source: "/best-pest-control-tucson-az", destination: "/tucson-az/pest-and-termite", permanent: true },
        { source: "/emergency-plumbing-tempe", destination: "/tempe-az/plumbing-and-water-heaters", permanent: true },
        { source: "/pest-control-mesa-az", destination: "/mesa-az/pest-and-termite", permanent: true },
        { source: "/gilbert-pest-control", destination: "/gilbert-az/pest-and-termite", permanent: true },
        { source: "/pest-control-gilbert-az", destination: "/gilbert-az/pest-and-termite", permanent: true },
        { source: "/pest-control-gilbert", destination: "/gilbert-az/pest-and-termite", permanent: true },
        { source: "/pest-control-tucson-az", destination: "/tucson-az/pest-and-termite", permanent: true },
        { source: "/mesa-pest-control", destination: "/mesa-az/pest-and-termite", permanent: true },
        { source: "/queen-creek-pest-control", destination: "/queen-creek-az/pest-and-termite", permanent: true },
        { source: "/tempe-ac-repair", destination: "/tempe-az/air-conditioning-and-heating/ac-repair", permanent: true },
        { source: "/phoenix-insulation", destination: "/phoenix-az/air-conditioning-and-heating/attic-insulation", permanent: true },
        { source: "/phoenix-air-conditioning-maintenance", destination: "/phoenix-az/air-conditioning-and-heating/ac-maintenance", permanent: true },
        { source: "/apache-junction-pest-control", destination: "/apache-junction-az/pest-and-termite", permanent: true },
        { source: "/pest-control-chandler-az", destination: "/chandler-az/pest-and-termite", permanent: true },
        { source: "/pest-control-chandler", destination: "/chandler-az/pest-and-termite", permanent: true },
        { source: "/pest-control-surprise-az", destination: "/surprise-az/pest-and-termite", permanent: true },
        { source: "/pest-control-sun-city-az", destination: "/sun-city-az/pest-and-termite", permanent: true },
        { source: "/pest-control-marana-az", destination: "/marana-az/pest-and-termite", permanent: true },
        { source: "/weed-control-marana-az", destination: "/marana-az/weed-and-lawn-care", permanent: true },
        { source: "/plumbing-phoenix", destination: "/phoenix-az/plumbing-and-water-heaters", permanent: true },
        { source: "/insulation-services", destination: "/phoenix-az/air-conditioning-and-heating/attic-insulation", permanent: true },
        // Homepage broken internal links (old WordPress URLs)
        { source: "/termite-warranty-registration", destination: "/termite-warranty", permanent: true },
        { source: "/termite-treatment-phoenix-az", destination: "/phoenix-az/pest-and-termite/termite-treatment", permanent: true },
        // Remaining broken internal links (full site crawl Jun 9)
        { source: "/financing", destination: "/request-service", permanent: true },
        { source: "/pest-control-phoenix-az", destination: "/phoenix-az/pest-and-termite", permanent: true },
        { source: "/phoenix/air-conditioning", destination: "/phoenix-az/air-conditioning-and-heating", permanent: true },
        { source: "/phoenix/duct-work", destination: "/phoenix-az/air-conditioning-and-heating/ductwork", permanent: true },
        { source: "/phoenix/heating", destination: "/phoenix-az/air-conditioning-and-heating/heating-repair", permanent: true },
        { source: "/phoenix/insulation", destination: "/phoenix-az/air-conditioning-and-heating/attic-insulation", permanent: true },
        { source: "/phoenix/plumbing-services", destination: "/phoenix-az/plumbing-and-water-heaters", permanent: true },
        { source: "/phoenix/water-heater", destination: "/phoenix-az/plumbing-and-water-heaters/water-heater-repair", permanent: true },
        { source: "/terms", destination: "/about", permanent: true },

        // ── City slugs without -az suffix → canonical -az slugs ──
        { source: "/apache-junction", destination: "/apache-junction-az", permanent: true },
        { source: "/mesa", destination: "/mesa-az", permanent: true },
        { source: "/gilbert", destination: "/gilbert-az", permanent: true },
        { source: "/chandler", destination: "/chandler-az", permanent: true },
        { source: "/tucson", destination: "/tucson-az", permanent: true },
        { source: "/scottsdale", destination: "/scottsdale-az", permanent: true },
        { source: "/tempe", destination: "/tempe-az", permanent: true },
        { source: "/peoria", destination: "/peoria-az", permanent: true },
        { source: "/surprise", destination: "/surprise-az", permanent: true },
        { source: "/goodyear", destination: "/goodyear-az", permanent: true },
        { source: "/buckeye", destination: "/buckeye-az", permanent: true },
        { source: "/queen-creek", destination: "/queen-creek-az", permanent: true },
        { source: "/san-tan-valley", destination: "/san-tan-valley-az", permanent: true },
        { source: "/gold-canyon", destination: "/gold-canyon-az", permanent: true },
        { source: "/phoenix", destination: "/phoenix-az", permanent: true },
        { source: "/marana", destination: "/marana-az", permanent: true },
        { source: "/oro-valley", destination: "/oro-valley-az", permanent: true },
        { source: "/ahwatukee", destination: "/ahwatukee-az", permanent: true },
        { source: "/anthem", destination: "/anthem-az", permanent: true },
        { source: "/casa-grande", destination: "/casa-grande-az", permanent: true },
        { source: "/coolidge", destination: "/coolidge-az", permanent: true },
        { source: "/florence", destination: "/florence-az", permanent: true },
        { source: "/fountain-hills", destination: "/fountain-hills-az", permanent: true },
        { source: "/laveen", destination: "/laveen-az", permanent: true },
        { source: "/litchfield-park", destination: "/litchfield-park-az", permanent: true },
        { source: "/maricopa", destination: "/maricopa-az", permanent: true },
        { source: "/paradise-valley", destination: "/paradise-valley-az", permanent: true },
        { source: "/catalina-foothills", destination: "/catalina-foothills-az", permanent: true },
        { source: "/green-valley", destination: "/green-valley-az", permanent: true },
        { source: "/sahuarita", destination: "/sahuarita-az", permanent: true },
        { source: "/vail", destination: "/vail-az", permanent: true },
        { source: "/valencia-west", destination: "/valencia-west-az", permanent: true },
        { source: "/red-rock", destination: "/red-rock-az", permanent: true },
        // Catch sub-paths too (e.g. /mesa/pest-and-termite → /mesa-az/pest-and-termite)
        { source: "/apache-junction/:path*", destination: "/apache-junction-az/:path*", permanent: true },
        { source: "/mesa/:path*", destination: "/mesa-az/:path*", permanent: true },
        { source: "/gilbert/:path*", destination: "/gilbert-az/:path*", permanent: true },
        { source: "/chandler/:path*", destination: "/chandler-az/:path*", permanent: true },
        { source: "/tucson/:path*", destination: "/tucson-az/:path*", permanent: true },
        { source: "/scottsdale/:path*", destination: "/scottsdale-az/:path*", permanent: true },
        { source: "/tempe/:path*", destination: "/tempe-az/:path*", permanent: true },
        { source: "/peoria/:path*", destination: "/peoria-az/:path*", permanent: true },
        { source: "/surprise/:path*", destination: "/surprise-az/:path*", permanent: true },
        { source: "/goodyear/:path*", destination: "/goodyear-az/:path*", permanent: true },
        { source: "/buckeye/:path*", destination: "/buckeye-az/:path*", permanent: true },
        { source: "/queen-creek/:path*", destination: "/queen-creek-az/:path*", permanent: true },
        { source: "/san-tan-valley/:path*", destination: "/san-tan-valley-az/:path*", permanent: true },
        { source: "/gold-canyon/:path*", destination: "/gold-canyon-az/:path*", permanent: true },
        // Phase 3: Remaining old WordPress pages still getting GSC impressions (2026-06-14)
        { source: "/phoenix/hvac-services/indoor-air-quality/air-filtration", destination: "/phoenix-az/air-conditioning-and-heating", permanent: true },
        { source: "/phoenix/hvac-services/indoor-air-quality/uv-light-installation", destination: "/phoenix-az/air-conditioning-and-heating", permanent: true },
        { source: "/phoenix/hvac-services/indoor-air-quality/dehumidifiers", destination: "/phoenix-az/air-conditioning-and-heating", permanent: true },
        { source: "/phoenix/hvac-services/indoor-air-quality/uv-air-purifiers", destination: "/phoenix-az/air-conditioning-and-heating", permanent: true },
        { source: "/phoenix/hvac-services/indoor-air-quality/air-balancing", destination: "/phoenix-az/air-conditioning-and-heating", permanent: true },
        { source: "/phoenix/hvac-services/indoor-air-quality", destination: "/phoenix-az/air-conditioning-and-heating", permanent: true },
        { source: "/phoenix/hvac-services/energy-efficiency", destination: "/phoenix-az/air-conditioning-and-heating", permanent: true },
        { source: "/phoenix/hvac-services", destination: "/phoenix-az/air-conditioning-and-heating", permanent: true },
        { source: "/phoenix/plumbing/hot-water-heater", destination: "/phoenix-az/plumbing-and-water-heaters/water-heater-repair", permanent: true },
        { source: "/phoenix/pest-control/weed-control", destination: "/phoenix-az/weed-and-lawn-care", permanent: true },
        { source: "/phoenix/pest-control/pest-library", destination: "/phoenix-az/pest-and-termite", permanent: true },
        { source: "/phoenix/hvac-services/installation", destination: "/phoenix-az/air-conditioning-and-heating/ac-installation", permanent: true },
        { source: "/phoenix/hvac-services/residential/heating-services/installation", destination: "/phoenix-az/air-conditioning-and-heating/heating-repair", permanent: true },
        { source: "/phoenix/hvac-services/residential/mini-splits", destination: "/phoenix-az/air-conditioning-and-heating/mini-split-systems", permanent: true },
        { source: "/phoenix/hvac-services/residential/ductless", destination: "/phoenix-az/air-conditioning-and-heating/mini-split-systems", permanent: true },
        { source: "/phoenix/refrigeration/repair", destination: "/phoenix-az/air-conditioning-and-heating", permanent: true },
        // ── 2026-06-24: Moved BEFORE wildcard — these were being swallowed by /phoenix/:path* ──
        { source: "/phoenix/hvac-services/replacement", destination: "/phoenix-az/air-conditioning-and-heating", permanent: true },
        { source: "/phoenix/hvac-services/residential/heat-pump-services/replacement", destination: "/phoenix-az/air-conditioning-and-heating", permanent: true },
        { source: "/phoenix/refrigeration/beer-coolers", destination: "/phoenix-az/air-conditioning-and-heating", permanent: true },
        { source: "/phoenix/refrigeration/installation", destination: "/phoenix-az/air-conditioning-and-heating", permanent: true },
        { source: "/phoenix/insulation/pest-guard", destination: "/phoenix-az/air-conditioning-and-heating/attic-insulation", permanent: true },
        { source: "/phoenix/insulation/duct-insulation", destination: "/phoenix-az/air-conditioning-and-heating/attic-insulation", permanent: true },
        // ── 2026-06-24: New redirect — WP blog slug → service page (blog post doesn't exist) ──
        { source: "/drain-cleaning-in-tucson-az-effective-clog-removal", destination: "/tucson-az/plumbing-and-water-heaters/drain-cleaning", permanent: true },
        { source: "/phoenix/:path*", destination: "/phoenix-az/:path*", permanent: true },
        { source: "/marana/:path*", destination: "/marana-az/:path*", permanent: true },
        { source: "/oro-valley/:path*", destination: "/oro-valley-az/:path*", permanent: true },

        // ── Priority SEO redirects — competitor-style flat URLs → silo structure ──
        // Scorpion control (monsoon season 2026 — URGENT)
        { source: "/scorpion-control-tucson-az", destination: "/tucson-az/pest-and-termite/scorpion-control", permanent: true },
        { source: "/scorpion-control-marana-az", destination: "/marana-az/pest-and-termite/scorpion-control", permanent: true },
        { source: "/scorpion-control-oro-valley-az", destination: "/oro-valley-az/pest-and-termite/scorpion-control", permanent: true },
        { source: "/scorpion-control-phoenix-az", destination: "/phoenix-az/pest-and-termite/scorpion-control", permanent: true },
        { source: "/scorpion-control-mesa-az", destination: "/mesa-az/pest-and-termite/scorpion-control", permanent: true },
        { source: "/scorpion-control-gilbert-az", destination: "/gilbert-az/pest-and-termite/scorpion-control", permanent: true },
        { source: "/scorpion-control-chandler-az", destination: "/chandler-az/pest-and-termite/scorpion-control", permanent: true },
        { source: "/scorpion-control-scottsdale-az", destination: "/scottsdale-az/pest-and-termite/scorpion-control", permanent: true },
        { source: "/scorpion-control-tempe-az", destination: "/tempe-az/pest-and-termite/scorpion-control", permanent: true },
        { source: "/scorpion-control-goodyear-az", destination: "/goodyear-az/pest-and-termite/scorpion-control", permanent: true },
        { source: "/scorpion-control-queen-creek-az", destination: "/queen-creek-az/pest-and-termite/scorpion-control", permanent: true },
        { source: "/scorpion-control-buckeye-az", destination: "/buckeye-az/pest-and-termite/scorpion-control", permanent: true },
        { source: "/scorpion-control-surprise-az", destination: "/surprise-az/pest-and-termite/scorpion-control", permanent: true },
        { source: "/scorpion-control-catalina-foothills-az", destination: "/catalina-foothills-az/pest-and-termite/scorpion-control", permanent: true },
        { source: "/scorpion-control-sahuarita-az", destination: "/sahuarita-az/pest-and-termite/scorpion-control", permanent: true },
        { source: "/scorpion-control-green-valley-az", destination: "/green-valley-az/pest-and-termite/scorpion-control", permanent: true },
        { source: "/scorpion-control-peoria-az", destination: "/peoria-az/pest-and-termite/scorpion-control", permanent: true },
        { source: "/scorpion-control-apache-junction-az", destination: "/apache-junction-az/pest-and-termite/scorpion-control", permanent: true },
        { source: "/scorpion-control-san-tan-valley-az", destination: "/san-tan-valley-az/pest-and-termite/scorpion-control", permanent: true },
        { source: "/scorpion-control-ahwatukee-az", destination: "/ahwatukee-az/pest-and-termite/scorpion-control", permanent: true },
        { source: "/scorpion-control-fountain-hills-az", destination: "/fountain-hills-az/pest-and-termite/scorpion-control", permanent: true },
        // Weed control
        { source: "/weed-control-goodyear-az", destination: "/goodyear-az/weed-and-lawn-care", permanent: true },
        { source: "/weed-control-tucson-az", destination: "/tucson-az/weed-and-lawn-care", permanent: true },
        { source: "/weed-control-oro-valley-az", destination: "/oro-valley-az/weed-and-lawn-care", permanent: true },
        { source: "/weed-control-phoenix-az", destination: "/phoenix-az/weed-and-lawn-care", permanent: true },
        { source: "/weed-control-mesa-az", destination: "/mesa-az/weed-and-lawn-care", permanent: true },
        { source: "/weed-control-gilbert-az", destination: "/gilbert-az/weed-and-lawn-care", permanent: true },
        { source: "/weed-control-chandler-az", destination: "/chandler-az/weed-and-lawn-care", permanent: true },
        { source: "/weed-control-scottsdale-az", destination: "/scottsdale-az/weed-and-lawn-care", permanent: true },
        { source: "/weed-control-surprise-az", destination: "/surprise-az/weed-and-lawn-care", permanent: true },
        { source: "/weed-control-buckeye-az", destination: "/buckeye-az/weed-and-lawn-care", permanent: true },
        { source: "/weed-control-peoria-az", destination: "/peoria-az/weed-and-lawn-care", permanent: true },
        // Pest control (additional cities not already covered)
        { source: "/pest-control-oro-valley-az", destination: "/oro-valley-az/pest-and-termite", permanent: true },
        { source: "/pest-control-scottsdale-az", destination: "/scottsdale-az/pest-and-termite", permanent: true },
        { source: "/pest-control-goodyear-az", destination: "/goodyear-az/pest-and-termite", permanent: true },
        { source: "/pest-control-tempe-az", destination: "/tempe-az/pest-and-termite", permanent: true },
        { source: "/pest-control-buckeye-az", destination: "/buckeye-az/pest-and-termite", permanent: true },
        { source: "/pest-control-queen-creek-az", destination: "/queen-creek-az/pest-and-termite", permanent: true },
        { source: "/pest-control-queen-creek", destination: "/queen-creek-az/pest-and-termite", permanent: true },
        { source: "/pest-control-glendale-az", destination: "/phoenix-az/pest-and-termite", permanent: true },
        { source: "/pest-control-glendale", destination: "/phoenix-az/pest-and-termite", permanent: true },
        { source: "/pest-control-scottsdale", destination: "/scottsdale-az/pest-and-termite", permanent: true },
        { source: "/pest-control-tempe", destination: "/tempe-az/pest-and-termite", permanent: true },
        { source: "/pest-control-mesa", destination: "/mesa-az/pest-and-termite", permanent: true },
        // Termite control
        { source: "/termite-control-tucson-az", destination: "/tucson-az/pest-and-termite/termite-treatment", permanent: true },
        { source: "/termite-control-marana-az", destination: "/marana-az/pest-and-termite/termite-treatment", permanent: true },
        { source: "/termite-control-oro-valley-az", destination: "/oro-valley-az/pest-and-termite/termite-treatment", permanent: true },
        // AC repair
        { source: "/ac-repair-phoenix-az", destination: "/phoenix-az/air-conditioning-and-heating/ac-repair", permanent: true },
        { source: "/ac-repair-mesa-az", destination: "/mesa-az/air-conditioning-and-heating/ac-repair", permanent: true },
        { source: "/ac-repair-gilbert-az", destination: "/gilbert-az/air-conditioning-and-heating/ac-repair", permanent: true },
        { source: "/ac-repair-chandler-az", destination: "/chandler-az/air-conditioning-and-heating/ac-repair", permanent: true },
        { source: "/ac-repair-scottsdale-az", destination: "/scottsdale-az/air-conditioning-and-heating/ac-repair", permanent: true },
        { source: "/ac-repair-goodyear-az", destination: "/goodyear-az/air-conditioning-and-heating/ac-repair", permanent: true },
        { source: "/hvac-repair", destination: "/phoenix-az/air-conditioning-and-heating", permanent: true },
        { source: "/ac-repair", destination: "/phoenix-az/air-conditioning-and-heating/ac-repair", permanent: true },

        // ── Old WordPress standard pages ──
        { source: "/about-us", destination: "/about", permanent: true },
        { source: "/testimonials", destination: "/reviews", permanent: true },
        { source: "/our-team", destination: "/about", permanent: true },
        { source: "/pricing", destination: "/request-service", permanent: true },
        { source: "/faq", destination: "/", permanent: true },
        { source: "/privacy-policy", destination: "/", permanent: true },
        { source: "/terms-of-service", destination: "/", permanent: true },
        { source: "/free-estimate", destination: "/request-service", permanent: true },
        { source: "/schedule", destination: "/request-service", permanent: true },
        { source: "/coupons", destination: "/", permanent: true },
        { source: "/specials", destination: "/", permanent: true },

        // ── Plumbing flat URL redirects (PHX metro) ──
        { source: "/plumber-mesa-az", destination: "/mesa-az/plumbing-and-water-heaters", permanent: true },
        { source: "/plumber-chandler-az", destination: "/chandler-az/plumbing-and-water-heaters", permanent: true },
        { source: "/plumber-gilbert-az", destination: "/gilbert-az/plumbing-and-water-heaters", permanent: true },
        { source: "/plumber-scottsdale-az", destination: "/scottsdale-az/plumbing-and-water-heaters", permanent: true },
        { source: "/plumber-tempe-az", destination: "/tempe-az/plumbing-and-water-heaters", permanent: true },
        { source: "/plumber-goodyear-az", destination: "/goodyear-az/plumbing-and-water-heaters", permanent: true },
        { source: "/plumber-surprise-az", destination: "/surprise-az/plumbing-and-water-heaters", permanent: true },
        { source: "/plumber-peoria-az", destination: "/peoria-az/plumbing-and-water-heaters", permanent: true },
        { source: "/plumber-buckeye-az", destination: "/buckeye-az/plumbing-and-water-heaters", permanent: true },
        { source: "/plumber-phoenix-az", destination: "/phoenix-az/plumbing-and-water-heaters", permanent: true },
        { source: "/plumber-queen-creek-az", destination: "/queen-creek-az/plumbing-and-water-heaters", permanent: true },
        // ── HVAC flat URL redirects (new cities) ──
        { source: "/ac-repair-tempe-az", destination: "/tempe-az/air-conditioning-and-heating/ac-repair", permanent: true },
        { source: "/ac-repair-surprise-az", destination: "/surprise-az/air-conditioning-and-heating/ac-repair", permanent: true },
        { source: "/ac-repair-peoria-az", destination: "/peoria-az/air-conditioning-and-heating/ac-repair", permanent: true },
        { source: "/ac-repair-buckeye-az", destination: "/buckeye-az/air-conditioning-and-heating/ac-repair", permanent: true },
        { source: "/hvac-phoenix-az", destination: "/phoenix-az/air-conditioning-and-heating", permanent: true },
        { source: "/hvac-mesa-az", destination: "/mesa-az/air-conditioning-and-heating", permanent: true },
        { source: "/hvac-chandler-az", destination: "/chandler-az/air-conditioning-and-heating", permanent: true },
        { source: "/hvac-gilbert-az", destination: "/gilbert-az/air-conditioning-and-heating", permanent: true },
        { source: "/hvac-scottsdale-az", destination: "/scottsdale-az/air-conditioning-and-heating", permanent: true },
        // ── Weed control additional cities ──
        { source: "/weed-control-tempe-az", destination: "/tempe-az/weed-and-lawn-care", permanent: true },
        { source: "/weed-control-queen-creek-az", destination: "/queen-creek-az/weed-and-lawn-care", permanent: true },
        { source: "/weed-control-san-tan-valley-az", destination: "/san-tan-valley-az/weed-and-lawn-care", permanent: true },
        { source: "/weed-control-litchfield-park-az", destination: "/litchfield-park-az/weed-and-lawn-care", permanent: true },
        { source: "/weed-control-fountain-hills-az", destination: "/fountain-hills-az/weed-and-lawn-care", permanent: true },
        // ── Pest control additional cities ──
        { source: "/pest-control-fountain-hills-az", destination: "/fountain-hills-az/pest-and-termite", permanent: true },
        { source: "/pest-control-peoria", destination: "/peoria-az/pest-and-termite", permanent: true },
        { source: "/pest-control-goodyear", destination: "/goodyear-az/pest-and-termite", permanent: true },
        { source: "/pest-control-surprise", destination: "/surprise-az/pest-and-termite", permanent: true },
        { source: "/pest-control-maricopa", destination: "/maricopa-az/pest-and-termite", permanent: true },
        { source: "/pest-control-florence", destination: "/florence-az/pest-and-termite", permanent: true },
        { source: "/pest-control-buckeye", destination: "/buckeye-az/pest-and-termite", permanent: true },
        { source: "/pest-control-avondale", destination: "/phoenix-az/pest-and-termite", permanent: true },
        { source: "/pest-control-tolleson", destination: "/phoenix-az/pest-and-termite", permanent: true },
        { source: "/pest-control-avondale-az", destination: "/phoenix-az/pest-and-termite", permanent: true },
        { source: "/pest-control-tolleson-az", destination: "/phoenix-az/pest-and-termite", permanent: true },
        { source: "/pest-control-maricopa-az", destination: "/maricopa-az/pest-and-termite", permanent: true },
        { source: "/pest-control-florence-az", destination: "/florence-az/pest-and-termite", permanent: true },

        // ── Orphaned blog slugs (old WordPress posts removed from blog data) ──
        { source: "/9-signs-of-bug-infestation-how-to-tell-if-you-have-a-pest-problem-in-your-home", destination: "/phoenix-az/pest-and-termite", permanent: true },
        { source: "/goodyear-plumbing-service-affordable-and-reliable-solutions", destination: "/goodyear-az/plumbing-and-water-heaters", permanent: true },
        { source: "/tempe-plumbing-solutions-quality-service-for-every-need", destination: "/tempe-az/plumbing-and-water-heaters", permanent: true },

        // ── Old WordPress service pages ──
        { source: "/pest-control-services", destination: "/phoenix-az/pest-and-termite", permanent: true },
        { source: "/hvac-services", destination: "/phoenix-az/air-conditioning-and-heating", permanent: true },
        { source: "/plumbing-services", destination: "/phoenix-az/plumbing-and-water-heaters", permanent: true },
        { source: "/services", destination: "/sitemap-page", permanent: true },
        { source: "/termite-treatment", destination: "/phoenix-az/pest-and-termite/termite-treatment", permanent: true },

        // ── WordPress remnants (stop Googlebot from crawling these) ──
        { source: "/wp-admin", destination: "/", permanent: true },
        { source: "/wp-login.php", destination: "/", permanent: true },
        { source: "/xmlrpc.php", destination: "/", permanent: true },
        { source: "/feed", destination: "/blog", permanent: true },
        { source: "/category/:path*", destination: "/blog", permanent: true },
        { source: "/author/:path*", destination: "/about", permanent: true },
        { source: "/wp-content/:path*", destination: "/", permanent: true },
        { source: "/wp-json/:path*", destination: "/", permanent: true },
        { source: "/wp-includes/:path*", destination: "/", permanent: true },
        // 2026-06-19: Batch fix — 12 new 404 URLs found via GSC full audit
        { source: "/blog/roach-control-near-skyline-regional-park-effective-solutions-for-buckeye-propert", destination: "/blog/roach-control-near-skyline-regional-park-effective-solutions-for-buckeye-propert-2", permanent: true },
        { source: "/glendale-az", destination: "/phoenix-az/pest-and-termite", permanent: true },
        { source: "/lennox", destination: "/phoenix-az/air-conditioning-and-heating", permanent: true },
        { source: "/maintenance-plans", destination: "/request-service", permanent: true },
        { source: "/snake-pest-control", destination: "/phoenix-az/pest-and-termite", permanent: true },
        { source: "/trane", destination: "/phoenix-az/air-conditioning-and-heating", permanent: true },
        { source: "/valencia-az", destination: "/chandler-az/pest-and-termite", permanent: true },
        { source: "/water-leak-detection-in-vail-az-professional-inspection-services", destination: "/vail-az/plumbing-and-water-heaters/leak-detection-repair", permanent: true },
        // 2026-06-21: Batch fix — 9 new 404 URLs found via GSC audit
        { source: "/blog/gilbert-cockroach-control-protecting-your-85297-area-home-year-round", destination: "/gilbert-az/pest-and-termite", permanent: true },
        { source: "/blog/getting-rid-of-fire-ants-in-gold-canyon-a-gold-canyon-ranch-homeowners-guide", destination: "/gold-canyon-az/pest-and-termite", permanent: true },
        { source: "/register", destination: "/request-service", permanent: true },
        { source: "/best-ac-repair-oro-valley-az-85737-maintenance-first-help-that-keeps-you-cool", destination: "/oro-valley-az/air-conditioning-and-heating", permanent: true },
        { source: "/tucson-energy-savings-why-insulation-beats-a-new-ac-95-of-the-time-v3", destination: "/tucson-az/air-conditioning-and-heating", permanent: true },
        { source: "/ac-repair-in-oro-valley-az-expert-cooling-support", destination: "/oro-valley-az/air-conditioning-and-heating", permanent: true },
        { source: "/tucson-plumbing-built-on-integrity-and-transparent-pricing", destination: "/tucson-az/plumbing-and-water-heaters", permanent: true },
        { source: "/news/how-to-keep-lawn-weed-free", destination: "/phoenix-az/weed-and-lawn-care", permanent: true },
        { source: "/water-heater-replacement-in-tucson-az-solving-hard-water-issues-for-good", destination: "/tucson-az/plumbing-and-water-heaters/water-heater-installation", permanent: true },
        // 2026-06-23: Batch fix — 4 new 404 URLs found via GSC audit
        { source: "/schedule-now", destination: "/request-service", permanent: true },
        { source: "/plumbing-services-in-marana-az-expert-solutions-for-every-household-need", destination: "/marana-az/plumbing-and-water-heaters", permanent: true },
        { source: "/tucson-home-comfort-why-insulation-is-the-secret-to-lower-energy-bills", destination: "/tucson-az/air-conditioning-and-heating/attic-insulation", permanent: true },
        // 2026-06-23: Catch-all for ALL root-level "best-*" blog URLs → /blog/
        // Replaces 16 individual redirects. Specific service-page redirects (best-pest-control-tucson-az,
        // best-ac-repair-oro-valley-az) are defined earlier and match first. Covers all ~174 legacy WordPress slugs.
        { source: "/:slug(best-.+)", destination: "/blog/:slug", permanent: true },
    ];
  },
};

export default nextConfig;
